### ISSUE TITLE
PayPal redirection

### ISSUE THREAD

**Issue by tbranyen** [haystack/tipsy#37]
For some reason PayPal isn't display a return link or redirect after making a payment.  What you can do for now is go back manually and remove the item from the log.

We'll need to investigate why.

**Comment by tbranyen** [comment]
What is happening here is that PayPal will refuse to redirect if only an email is provided.  Instead we need to get access to the token created during Donate Link generation to enable redirection.

**Comment by tbranyen** [comment]
I've tried many things to make PayPal work the way it's documented.  If you look [here](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/) in the PayPal documentation, you'll see a `return` property is documented as a URL that will send the user back to after successful payment.  There's also a `cancel_return` url property for the case of canceling a payment.

Problem is that neither of these properties are being respected by PayPal.  I've tried all sorts of combinations, including using the generated token approach.  We need to use these runtime configurations because the return URL may change in the future so statically hardcoding a return value is not a long-term option.

The static coding of the URL does work if a user was to "pre-fill" these values inside the donation button generation form.  Basically we'd have to tell them to input a url for both the return and cancel options and to update them if our return URL ever changes.

I'm going to ping PayPal directly and see what I can find out, because it should work as-is.

**Comment by karger** [comment]
If you have trouble getting a response let me know---I might have a 
back-channel to paypal.

**Comment by schilippe** [comment]
@tbranyen have you heard anything from PayPal?

**Comment by tbranyen** [comment]
Yup:

> Hello Tim Branyen,
>
> That's fine if you are dynamically creating the cancel and return URL. The problem is the hosted button ID. It does not exist in your PayPal account. You will have to use a hosted button ID that is saved in your account or create non hosted buttons that do not include hosted button IDs.
Sincerely,
Virgil
PayPal, an eBay Company

So it looks like it's possible, I'll have to dig a bit more and figure out how to use a non-hosted button.

**Comment by tbranyen** [comment]
Figured out this problem.  Turns out PayPal accepts return urls just fine, just not ones that are IP addresses.  I converted to a hostname and it works fine.  Ideally though we'll have a dedicated Tipsy address endpoint that I can map my redirect server script to.

Can @karger or @schilippe provision an endpoint for the Node script to live at?  Ideally something like this:  `http://tipsy.csail.mit.edu/redirect/<encoded uri>` What I need is an endpoint proxied to a localhost port `9999` or something similar.  In nginx this would look like:

``` nginx
server {                                                                           
  listen 80;                                                                       
  server_name tipsy.csail.mit.edu;                                                     
                                                                                   
  location /redirect {                                                                     
    proxy_pass http://127.0.0.1:9999;                                              
  }                                                                                
}                                                                                  
```

BTW This is excellent news, because it keeps PayPal super simple and unchanged.  All we need from the content creator is an email address.

**Comment by schilippe** [comment]
This is great news! We can keep it all within the CSAIL afs. Have you been able to set up a CSAIL account?

**Comment by tbranyen** [comment]
[PR with working Paypal](https://github.com/haystack/tipsy/pull/62)

**Comment by schilippe** [comment]
Nice. Once this PR passes travis and is merged with master perhaps we should merge the other daysWithVisited branch back into it to prevent too much divergence. (I see from the PR that here might be small merge conflicts already.)
