### ISSUE TITLE
X's to delete rows in contributions page

### ISSUE THREAD

**Issue by schilippe** [haystack/tipsy#72]
@tbranyen They somehow disappeared.

**Comment by tbranyen** [comment]
Darn, I bet that happened when I adjusted the table layout to fixed.

**Comment by schilippe** [comment]
Didn't realize you self-assigned. I had to add the tooltip and confirm box anyway...

**Comment by schilippe** [comment]
X's still don't appear nicely on small screens

**Comment by tbranyen** [comment]
@schilippe can you see if the latest master (777ee5fed73cf7d55ee2e507b12817b7e4f8c295) works for you? at super small resolutions they disappear with my fix, but so does most of the table data.  I'll look into integrating something like: https://github.com/filamentgroup/tablesaw

**Comment by schilippe** [comment]
Thanks! It works now. THe Xs are a bit low on wide screen but at least they don't overlap with the table anymore.

**Comment by tbranyen** [comment]
I think we can close this issue out.
